[tool.poetry]
name = "arche"
version = "0.1.0"
description = "state management for pygame"
authors = ["fxxf <fxxf@tutanota.com>"]

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
